//
//  FetchPentateucoUseCase.swift
//  BibliaSagradaDatabase
//
//  Created by Rodrigo Soldi on 03/01/25.
//  Copyright (c) 2025 Soldi Inc.. All rights reserved.
//
//  This file was generated by Rodrigo Soldi
//

public protocol FetchPentateucoUseCase {
    func execute() async throws -> [Book]
}

public struct FetchPentateucoUseCaseImpl: FetchPentateucoUseCase {

    private typealias K = Constants
    private struct Constants {
        static let booksIDs: [Int] = [1, 2, 3, 4, 5]
    }

    private let bibleRepository: BibleRepository
    
    public init() {
        try! self.init(bibleRepository: BibleRepositoryImpl())
    }
    
    init(bibleRepository: BibleRepository) {
        self.bibleRepository = bibleRepository
    }

    public func execute() async throws -> [Book] {
        try await bibleRepository.fetchBooks(booksIDs: K.booksIDs)
    }
    
}
