//
//  FetchBooksFromSectionUseCase.swift
//  BibliaSagradaDatabase
//
//  Created by Rodrigo Soldi on 03/01/25.
//  Copyright (c) 2025 Soldi Inc.. All rights reserved.
//
//  This file was generated by Rodrigo Soldi
//

public protocol FetchBooksFromSectionUseCase {
    func execute(_ bookSection: BookSection) async throws -> [Book]
}

public struct FetchBooksFromSectionUseCaseImpl: FetchBooksFromSectionUseCase {

    private typealias K = Constants
    private struct Constants {

    }
    
    private let bibleRepository: BibleRepository
    
    public init() {
        try! self.init(bibleRepository: BibleRepositoryImpl())
    }
    
    init(bibleRepository: BibleRepository) {
        self.bibleRepository = bibleRepository
    }

    public func execute(_ bookSection: BookSection) async throws -> [Book] {
        try await bibleRepository.fetchBooks(booksIDs: bookSection.bookIDs)        
    }

}
