//
//  FetchBibleUseCase.swift
//  BibliaSagradaDatabase
//
//  Created by Rodrigo Soldi on 01/01/25.
//  Copyright (c) 2025 Soldi Inc.. All rights reserved.
//
//  This file was generated by Rodrigo Soldi
//

public protocol FetchBibleUseCase {
    func execute() async throws -> Bible
}

public struct FetchBibleUseCaseImpl: FetchBibleUseCase {

    private typealias K = Constants
    private struct Constants {

    }
    
    private let bibleRepository: BibleRepository
    
    public init() {
        try! self.init(bibleRepository: BibleRepositoryImpl())
    }
    
    init(bibleRepository: BibleRepository) {
        self.bibleRepository = bibleRepository
    }

    public func execute() async throws -> Bible {
        try await bibleRepository.fetchBible()
    }

}
