//
//  FetchBookSectionsUseCase.swift
//  BibliaSagradaDatabase
//
//  Created by Rodrigo Soldi on 03/01/25.
//  Copyright (c) 2025 Soldi Inc.. All rights reserved.
//
//  This file was generated by Rodrigo Soldi
//

public protocol FetchBookSectionsUseCase {
    func execute() async throws -> [BookSection]
}

public struct FetchBookSectionsUseCaseImpl: FetchBookSectionsUseCase {

    private typealias K = Constants
    private struct Constants {
        static let pentateuco: [Int] = Array(1...5) // Gênesis a Deuteronômio
        static let historicos: [Int] = Array(6...17) // Josué a Ester
        static let poeticos: [Int] = Array(18...22) // Jó a Cântico dos Cânticos
        static let profetasMaiores: [Int] = Array(23...27) // Isaías a Daniel
        static let profetasMenores: [Int] = Array(28...39) // Oseias a Malaquias
        static let evangelhos: [Int] = Array(40...43) // Mateus a João
        static let atosDosApostolos: [Int] = [44] // Apenas Atos
        static let cartasPaulinas: [Int] = Array(45...57) // Romanos a Filemom
        static let cartasGerais: [Int] = Array(58...65) // Hebreus a Judas
        static let apocalipse: [Int] = [73] // Apenas Apocalipse
    }

    public func execute() async throws -> [BookSection] {
        return [
            BookSection(
                title: "Pentateuco",
                type: .pentateuco,
                bookIDs: K.pentateuco),
            BookSection(
                title: "Históricos",
                type: .historicos,
                bookIDs: K.historicos),
            BookSection(
                title: "Poéticos",
                type: .poeticos,
                bookIDs: K.poeticos),
            BookSection(
                title: "Profetas Maiores",
                type: .profetasMaiores,
                bookIDs: K.profetasMaiores),
            BookSection(
                title: "Profetas Menores",
                type: .profetasMenores,
                bookIDs: K.profetasMenores),
            BookSection(
                title: "Evangelhos",
                type: .evangelhos,
                bookIDs: K.evangelhos),
            BookSection(
                title: "Atos dos Apóstolos",
                type: .atosDosApostolos,
                bookIDs: K.atosDosApostolos),
            BookSection(
                title: "Cartas Paulinas",
                type: .cartasPaulinas,
                bookIDs: K.cartasPaulinas),
            BookSection(
                title: "Cartas Gerais",
                type: .cartasGerais,
                bookIDs: K.cartasGerais),
            BookSection(
                title: "Apocalipse",
                type: .apocalipse,
                bookIDs: K.apocalipse)
        ]
    }

}
